### PR TITLE
Updated simulator notebook, fix for single pitch, protections for bad conditions.

### LINKED ISSUE #42: Why does sonification not work if only two values present?
For transit simulator or case of top of square (e.g., square wave) the output sound isn't as expected.  One would expect two distinct sounds at roughly 1/3 and 2/3 the allowed tone range, but instead it is basically monotone.  This could be a bug, or could be result of algorithm being used, will investigate.

### LINKED ISSUE #43: Fix bug when given array of all the same value.
There's a known bug where if given an array that all the same flux value it returns the data zero point instead of the center ptich value.

### PR DESCRIPTION
**Pull request by scfleming**
This PR:

- Fixes #43 where in case of single value will return center pitch.
- Updates simulator notebook to produce better sounds in transit cases by using better choices of zero point (doesn't rely on default median value, which is a poor choice in the simple case of two values).  This effecively closes #42, at least for now.
- Fixes small bug when creating output directory in sim_lc.py.
- pitch_mapper() did not protect against a center pitch value that didn't fall within the pitch range. It now will check and if the center_pitch value is outside or equal to the bounds of the pitch_range, will fall back to define the center_pitch to be the middle of the range. May want to inform the user in some manner as a future PR if so?
- In rare cases (e.g., array of two flux values where median() is also the lowest of the two values) the default algorithm parameter choices result in a zero_point that is 0.0, which then results in an error divide by zero.  To protect against this, pitch_mapper() will instead set the zero_point value to a small number (currently 1E-6) to avoid the division by zero.  Normally this is because the user made a poor choice of sonification parameters, we should consider giving them more diagnostics in the case where their data+parameters result in bad distributions of pitches?  Something to consider for the future perhaps?
- Minor style changes to satisfy pylint to the code I touched.

### CODE REVIEW

**Comment by scfleming** [comment]
@ceb8 I updated the .pynb but don't know the steps to convert to HTML for RTD (do you just run nbconvert on them?)  Would you be able to take care of that part?

**Comment by ceb8** [comment]
@scfleming  This looks great! I'm going to run the ipynb->rst before merging. Unfortunately right now it's more manual than I would like.

**Comment by ceb8** [comment]
@scfleming Remember to clear the output before commiting jupyter notebooks. (I'm going to deal with it by squashing when I merge this PR).

**Comment by scfleming** [comment]
Oh, I thought it needed to be there so nbconvert would display things like the plots in the rendered HTML. My bad.

**Comment by ceb8** [comment]
Thanks @scfleming !

**Pull request merged**
